### PR TITLE
CDC firmware

### PR DESCRIPTION
**Pull request by laborleben**
pyTLU firmware with proper clock domain crossing.

A quick test showed no issues.

### CODE REVIEW

**Comment by themperek** [comment]
Does it work?

**Comment by laborleben** [comment]
Yes, but needs to be tested together with a device.

**Comment by themperek** [comment]
@YannickDieter Can you check this somehow?

**Comment by themperek** [comment]
Thank you @laborleben Maybe some issues on cdc. 
Will test and merge.

**Comment by YannickDieter** [comment]
I can test this at the next ELSA TB (26/11-27/11).

**Comment by YannickDieter** [comment]
Seems to work. I checked the new FW during Testbeam. During 2e6 triggers no jump was observed. Tested with TLU v0.2a PC017b.

image

There is also no jump detected in the tlu.h5 file.

**Pull request merged**
