### PR TITLE
v1.0.0 release 

### PR DESCRIPTION
**Pull request by YannickDieter**

### CODE REVIEW

**Comment by YannickDieter** [comment]
Sorry, I missed something with the .bit file which is not up-to-date. I will upload the correct version!

**Comment by YannickDieter** [comment]
Sorry... I completely messed up everything after my rebase. I force pushed again to the HEAD before the rebase. The merge and release I will do after the testbeam....

**Comment by laborleben** [comment]
Leave it as it is. I'll fix that tomorrow, or if you like check out git reflog and do a reset --hard and start all over again.

**Comment by YannickDieter** [comment]
Yes this D did already and everything is now as it was before the rebase. git reflog was my luck :). If you want you can rebase tomorrow.

**Pull request closed without merging**
